%YAML:1.0
cfg_1: 1.0        #Scale[0]
cfg_2: 1.0        #Scale[1]
cfg_3: 0.0        #Rotate
cfg_4: 0.0        #Translate[0] left right move 1.0 for right half
cfg_5: -0.0       #Translate[1] top down move 1.0 for top half

